/**
 * default_agent_tools.js - Default Subject-Neutral Activity Projections for Retos 1-6
 */
module.exports = {
    "1": {
        es: "Opción 1: Buscar tres fuentes confiables sobre un tema libre de estudio y registrar sus enlaces y autores en un documento compartido.\nOpción 2: Crear un glosario colaborativo de términos clave de la asignatura usando un editor de texto en la nube.\nOpción 3: Organizar una estructura de carpetas digitales con nombres claros en OneDrive o Drive para clasificar la información de la clase.",
        de: "Option 1: Suche nach drei vertrauenswürdigen Quellen zu einem freien Thema und halte Links und Autoren in einem geteilten Dokument fest.\nOption 2: Erstelle ein kollaboratives Glossar der Schlüsselbegriffe des Fachs in einem Online-Texteditor.\nOption 3: Organisiere eine digitale Ordnerstruktur mit klaren Namen in OneDrive oder Drive, um Unterrichtsmaterialien zu sortieren.",
        en: "Option 1: Search for three reliable sources on a chosen topic and record their links and authors in a shared document.\nOption 2: Create a collaborative glossary of key terms for the subject using a cloud text editor.\nOption 3: Organize a digital folder structure with clear names in OneDrive or Drive to classify class materials."
    },
    "2": {
        es: "Opción 1: Realizar una lluvia de ideas colaborativa sobre un tema de clase en una pizarra digital interactiva (como Padlet o Miro).\nOpción 2: Redactar de forma grupal un código de conducta o 'netiqueta' para la comunicación digital escolar.\nOpción 3: Participar en un foro de discusión digital de la plataforma escolar, respondiendo de forma respetuosa a las opiniones de dos compañeros.",
        de: "Option 1: Führe ein kollaboratives Brainstorming zu einem freien Thema auf einem digitalen Whiteboard (z.B. Padlet oder Miro) durch.\nOption 2: Verfasse in der Gruppe einen Verhaltenskodex ('Netiquette') für die digitale schulische Kommunikation.\nOption 3: Nimm an einem digitalen Diskussionsforum auf der Schulplattform teil und antworte respektvoll auf die Beiträge von zwei Mitschülern.",
        en: "Option 1: Conduct a collaborative brainstorming session on a digital whiteboard (like Padlet or Miro).\nOption 2: Group-write a code of conduct ('netiquette') for digital school communication.\nOption 3: Participate in a digital school platform forum, responding respectfully to the posts of two classmates."
    },
    "3": {
        es: "Opción 1: Diseñar una infografía explicativa en Canva que resuma los conceptos clave de un tema libre.\nOpción 2: Crear una presentación digital interactiva utilizando PowerPoint o Slides, aplicando derechos de autor en las imágenes usadas.\nOpción 3: Grabar un videoclip corto o podcast (audio) explicando un aprendizaje o conclusión de la asignatura.",
        de: "Option 1: Gestalte eine erklärende Infografik in Canva, die die Kernkonzepte eines freien Themas zusammenfasst.\nOption 2: Erstelle eine interaktive digitale Präsentation mit PowerPoint oder Slides und beachte dabei das Urheberrecht der verwendeten Bilder.\nOption 3: Nimm ein kurzes Erklärvideo oder einen Podcast (Audio) auf, um ein Lernergebnis des Fachs zu präsentieren.",
        en: "Option 1: Design an explanatory infographic in Canva summarizing key concepts of a chosen topic.\nOption 2: Create an interactive digital presentation using PowerPoint or Slides, respecting copyright licenses for all images used.\nOption 3: Record a short video clip or podcast (audio) explaining a learning outcome or conclusion for the subject."
    },
    "4": {
        es: "Opción 1: Elaborar un decálogo ilustrado en Canva sobre cómo crear contraseñas seguras y proteger la privacidad en internet.\nOpción 2: Diseñar un folleto informativo sobre la ergonomía física frente a pantallas y la importancia de equilibrar el tiempo digital.\nOpción 3: Crear un cartel digital sobre el impacto ambiental del uso de dispositivos tecnológicos y cómo reciclarlos de forma responsable.",
        de: "Option 1: Erstelle ein illustriertes Plakat in Canva darüber, wie man sichere Passwörter erstellt und die Privatsphäre im Internet schützt.\nOption 2: Gestalte eine Informationsbroschüre über Ergonomie vor dem Bildschirm und die Bedeutung einer gesunden Bildschirmzeit.\nOption 3: Erstelle ein digitales Poster über die Umweltauswirkungen digitaler Geräte und wie man sie verantwortungsvoll recycelt.",
        en: "Option 1: Create an illustrated guide in Canva on how to create secure passwords and protect internet privacy.\nOption 2: Design an information brochure about screen ergonomics and the importance of healthy screen time limits.\nOption 3: Create a digital poster about the environmental impact of technological devices and how to recycle them responsibly."
    },
    "5": {
        es: "Opción 1: Diseñar un mapa mental digital estructurado que organice soluciones para un problema práctico de la clase.\nOpción 2: Crear un diagrama de flujo interactivo para representar un algoritmo o secuencia lógica paso a paso.\nOpción 3: Redactar una guía de solución de fallas técnicas comunes (ej. problemas de sonido, cámara o conexión a internet) para ayudar a otros estudiantes.",
        de: "Option 1: Erstelle eine strukturierte digitale Mindmap, die Lösungen für ein praktisches Problem des Unterrichts ordnet.\nOption 2: Gestalte ein interaktives Flussdiagramm, um einen Algorithmus oder eine logische Schritt-für-Schritt-Folge darzustellen.\nOption 3: Verfasse eine Anleitung zur Behebung häufiger technischer Fehler (z.B. Ton-, Kamera- oder Internetprobleme), um Mitschülern zu helfen.",
        en: "Option 1: Create a structured digital mind map organizing solutions to a practical classroom problem.\nOption 2: Design an interactive flowchart representing a step-by-step algorithm or logical sequence.\nOption 3: Write a troubleshooting guide for common technical issues (e.g., sound, camera, or internet problems) to help other students."
    },
    "6": {
        es: "Opción 1: Realizar un análisis comparativo en Canva sobre la influencia de las redes sociales y la publicidad en la toma de decisiones.\nOpción 2: Crear una infografía sobre el uso seguro del internet, evaluando críticamente cómo distinguir noticias reales de falsas.\nOpción 3: Elaborar un cuadro comparativo digital sobre el impacto económico y social de las nuevas tecnologías en la vida diaria.",
        de: "Option 1: Führe eine vergleichende Analyse in Canva über den Einfluss sozialer Medien und Werbung auf die Entscheidungsfindung durch.\nOption 2: Erstelle eine Infografik zur sicheren Internetnutzung und bewerte kritisch, wie man echte von falschen Nachrichten unterscheidet.\nOption 3: Erstelle eine digitale Tabelle über die wirtschaftlichen und sozialen Auswirkungen neuer Technologien auf das tägliche Leben.",
        en: "Option 1: Conduct a comparative analysis in Canva on the influence of social media and advertising on decision making.\nOption 2: Create an infographic about safe internet use, critically evaluating how to distinguish real news from fake news.\nOption 3: Produce a digital comparison chart about the economic and social impact of new technologies on daily life."
    }
};
